language: swift
osx_image: xcode7.2
xcode_project: TMModel.xcodeproj
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: TMModel
xcode_sdk: iphonesimulator9.2
env:
  global: 
    - FRAMEWORK_NAME=TMModel
before_install:
  - brew update
  - brew install carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap  
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME

skip_cleanup: true
on:
  repo: repo/repo
  tags: true
